### ISSUE TITLE
Reference file

### ISSUE THREAD

**Issue by Maureiq** [ncsu-landscape-dynamics/weather-coefficient#7]
Add the reference file us_states_lccproj.shp as a function parameter, not a hardcoded path.

**Comment by ChrisJones687** [comment]
Done in Release branch. Will push to master after testing. Note that reference_area and states_file need to be in the same projection as Daymet data. Also, states_file needs to have a field STATE_NAME, typically found in most US state boundary shapefiles.

**Comment by Maureiq** [comment]
Thank you!
