### ISSUE TITLE
Error running test_weather-coefficient

### ISSUE THREAD

**Issue by Maureiq** [ncsu-landscape-dynamics/weather-coefficient#8]
I get this error when I run the test_weather-coeffient.R as it is.
**Error:**
Integer64 fields read as strings:  
OBJECTID 
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
Error in `names<-`(`*tmp*`, value = unique(format(as.Date(names(prcp),  : 
  incorrect number of layer names
The projection of my Daymet and reference files is the same.
**Reference file**
Dataset PROJ_INFO is:
name: Lambert_Conformal_Conic
datum: wgs84
ellps: wgs84
proj: lcc
lat_1: 25
lat_2: 60
lat_0: 42.5
lon_0: -100
x_0: 0
y_0: 0

**And the daymet files:**
Proj4 = "+proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-100 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs"
Min X = "-5802750"
Min Y = "-3090500"
Max X = "3809250"
Max Y = "4984500"
Processing Level = "3"

**Comment by ChrisJones687** [comment]
If you could share a google drive folder with the data and an R script with the parameters I can test it to see where exactly the error is occurring and work on a fix.

**Comment by Maureiq** [comment]
https://drive.google.com/open?id=1SDMl7dQklcqArJAOHz1xJbIEx0f08g5E

**Comment by ChrisJones687** [comment]
Thanks! I finally ran through this using this using the us_states_lccproj.shp from your folder and the Daymet data from our internal locations and had no errors. 

Did you save your Daymet files with the exact names that they suggest when downloading them? The function uses the naming convention from Daymet as a way to name the files.
