### ISSUE TITLE
Setting temp susceptibility index to 1

### ISSUE THREAD

**Issue by Maureiq** [ncsu-landscape-dynamics/weather-coefficient#9]
I want to set the temp suitability index = 1 and 0.5 and try getting running the test_weather_coeffient.R. I think I should do this by setting the temp_index=YES, temp_method = "reclass" and all the temp_a* coefficients to 0. Please advice on what I should do with the temp_matrix. All I have from the documentation is "temp_matrix - Matrix used to reclassify temperatures only used if temp_method = 'reclass'". I need this because I don't have a regression model that to "express temperature x as a suitability index y by fitting a cubic polynomial (y 1⁄4􏰁0.066 þ 0.056x 􏰁 0.0036(x 􏰁 15)2 􏰁 0.0003(x 􏰁 15)3) to these rescaled data (n 1⁄4 14, R2 1⁄4 0.79)"

**Comment by ChrisJones687** [comment]
For testing purposes, I would set up something like this. 
temp_mat <- c(-Inf, -12, 0, 
              -12, 0, 0.5,
              0, 30, 1,
              30, 35 , 0.5,
              35, Inf, 0)♥
temp_matrix <- matrix(temp_mat, ncol=3, byrow=TRUE)

This will give you a reclass where temperatures values below -12 and above 35 are 0
values between -12 and 0 and 30 to 35 become 0.5
and values between 0 and 30 become 1

If you want to set up a meeting to chat sometime just send an email.
